### ISSUE TITLE
RTK cert expired

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/infrastructure#152]
`/var/log/letsencrypt/letsencrypt.log` shows:

```
2020-07-27 07:16:52,065:WARNING:certbot.renewal:Attempting to renew cert (test.righttoknow.org.au) from /etc/letsencrypt/renewal/test.righttoknow.org.au.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for test.righttoknow.org.au:. Skipping.
2020-07-27 07:16:52,065:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 452, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1193, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 310, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/webroot.py", line 81, in perform
    self._set_webroots(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/webroot.py", line 99, in _set_webroots
    known_webroots)
  File "/usr/lib/python3/dist-packages/certbot/plugins/webroot.py", line 120, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain, True)
  File "/usr/lib/python3/dist-packages/certbot/plugins/webroot.py", line 144, in _prompt_for_new_webroot
    force_interactive=True)
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 372, in validated_directory
    validator, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/certbot/display/ops.py", line 329, in _get_validated
    code, raw = method(message, default=default, **kwargs)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 583, in directory_select
    return self.input(message, default, cli_flag)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 524, in input
    self._interaction_fail(message, cli_flag)
  File "/usr/lib/python3/dist-packages/certbot/display/util.py", line 469, in _interaction_fail
    raise errors.MissingCommandlineFlag(msg)
certbot.errors.MissingCommandlineFlag: Missing command line flag or config entry for this setting:
Input the webroot for test.righttoknow.org.au:
```

**Comment by jamezpolley** [comment]
The renewal configs do have a webroot parameter in them:

```
webroot_path = /usr/share/nginx/html,
[[webroot_map]]
```

but running `letsencrypt renew` is still complaining about not seeing the path:
```
Attempting to renew cert (righttoknow.org.au) from /etc/letsencrypt/renewal/righttoknow.org.au.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for righttoknow.org.au:. Skipping.
```

I'm not sure if that's a syntax thing (maybe the comma shouldn't be there?) or if renew doesn't pay attention to the webroot parameter

**Comment by jamezpolley** [comment]
Using the `update-ssl-certs.yml` playbook I was able to fix the renewal config:

```
ansible-playbook update-ssl-certs.yml -l righttoknow
....
TASK [Force certificates to be renewed with webroot] **************************************************************************************************************************
changed: [righttoknow.org.au]

PLAY RECAP ********************************************************************************************************************************************************************
righttoknow.org.au         : ok=2    changed=1    unreachable=0    failed=0
```

Renewal config now has content in the webroot map:

```
webroot_path = /usr/share/nginx/html,
[[webroot_map]]
www.righttoknow.org.au = /usr/share/nginx/html
righttoknow.org.au = /usr/share/nginx/html
```

and the certs has been regenerated.

I've been able to renew the certificates with this config:

```
root@ip-172-31-43-31:/etc/letsencrypt/renewal# letsencrypt renew --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/righttoknow.org.au.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator webroot, Installer nginx
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed with reload of nginx server; fullchain is
/etc/letsencrypt/live/righttoknow.org.au/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/test.righttoknow.org.au.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator webroot, Installer nginx
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Renewing an existing certificate

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed with reload of nginx server; fullchain is
/etc/letsencrypt/live/test.righttoknow.org.au/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/righttoknow.org.au/fullchain.pem (success)
  /etc/letsencrypt/live/test.righttoknow.org.au/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

so I'm not expecting a repeat.

**Comment by mlandauer** [comment]
Thanks @jamezpolley!
